apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: audio-to-text-gitlab-test-new1
  janus-idp.io/tekton: audio-to-text-gitlab-test-new1
  backstage.io/kubernetes-id: audio-to-text-gitlab-test-new1
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: audio-to-text-gitlab-test-new1
resources:
  - application-dev.yaml