apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: audio-to-text-gitlab-test-new1-gitops-repository
spec:
  url: https://github.com/rhdh-JslYoon-org/audio-to-text-gitlab-test-new1-gitops
