apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: audio-to-text-gitlab-test-new1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rh-ee-lyoon-dh/audio-to-text-gitlab-test-new1:700c59e31155229f8db90d6c7c024552433e8c2c@sha256:045c9b7ac4a686b839a06ce321fde3127ac6700712d427b6f02c676106a52005 # use pre-built to bootstrap
          name: app-inference
